config/routes.rb
# == Route Map
#
#              Prefix Verb   URI Pattern                          Controller#Action
#                root GET    /                                    home#index
#               about GET    /about(.:format)                     about#index
#       users_sign_up POST   /users/sign_up(.:format)             users/sign_up#create
#                     GET    /users/sign_up(.:format)             users/sign_up#show
#       users_sign_in POST   /users/sign_in(.:format)             users/sign_in#create
#                     GET    /users/sign_in(.:format)             users/sign_in#show
#      users_sign_out DELETE /users/sign_out(.:format)            users/sign_out#destroy
#         users_posts GET    /users/posts(.:format)               users/posts#index
#                     POST   /users/posts(.:format)               users/posts#create
#      new_users_post GET    /users/posts/new(.:format)           users/posts#new
#     edit_users_post GET    /users/posts/:id/edit(.:format)      users/posts#edit
#          users_post GET    /users/posts/:id(.:format)           users/posts#show
#                     PATCH  /users/posts/:id(.:format)           users/posts#update
#                     PUT    /users/posts/:id(.:format)           users/posts#update
#                     DELETE /users/posts/:id(.:format)           users/posts#destroy
#    users_categories GET    /users/categories(.:format)          users/categories#index
#                     POST   /users/categories(.:format)          users/categories#create
#  new_users_category GET    /users/categories/new(.:format)      users/categories#new
# edit_users_category GET    /users/categories/:id/edit(.:format) users/categories#edit
#      users_category GET    /users/categories/:id(.:format)      users/categories#show
#                     PATCH  /users/categories/:id(.:format)      users/categories#update
#                     PUT    /users/categories/:id(.:format)      users/categories#update
#                     DELETE /users/categories/:id(.:format)      users/categories#destroy
#          users_tags GET    /users/tags(.:format)                users/tags#index
#                     POST   /users/tags(.:format)                users/tags#create
#       new_users_tag GET    /users/tags/new(.:format)            users/tags#new
#      tag_list_users GET    /users/tag/list(.:format)            users/tags#list
#          edit_users GET    /users/edit(.:format)                users#edit
#               users GET    /users(.:format)                     users#show
#                     PATCH  /users(.:format)                     users#update
#                     PUT    /users(.:format)                     users#update
#                     DELETE /users(.:format)                     users#destroy
#          blog_posts GET    /blog/posts(.:format)                blog/posts#index
#           blog_post GET    /blog/posts/:id(.:format)            blog/posts#show
#       blog_category GET    /blog/categories/:id(.:format)       blog/categories#show
#            blog_tag GET    /blog/tags/:id(.:format)             blog/tags#show
#

Rails.application.routes.draw do
  root 'home#index'
  get 'profile', to: 'profile#index'

  resource :users, only: [:show, :edit, :update, :destroy] do
    resource :sign_up, controller: 'users/sign_up', only: [:show, :create]
    resource :sign_in, controller: 'users/sign_in', only: [:show, :create]
    resource :sign_out, controller: 'users/sign_out', only: [:destroy]
    resources :posts, controller: 'users/posts'
    resources :categories, controller: 'users/categories'
    resources :tags, controller: 'users/tags', only: [:index, :create, :new]
    get 'tag/list', to: 'users/tags#list'
  end

  namespace :blog do
    resources :posts, only: [:index, :show]
    resources :categories, only: [:show]
    resources :tags, only: [:show]
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  category_id :integer
#  title       :string(255)
#  body        :text(65535)
#  status      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Post < ActiveRecord::Base
  RECENT_POSTS_CONT = 5
  LATEST_POSTS_COUNT = 3

  acts_as_taggable

  enum status: { wip: 0, published: 1 }

  belongs_to :category
  belongs_to :user

  accepts_nested_attributes_for :tags,
                                reject_if: :all_blank,
                                allow_destroy: true

  validates :title,
            presence: true
  validates :body,
            presence: true
  validates :category_id,
            presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                              :integer          not null, primary key
#  name                            :string(255)      not null
#  email                           :string(255)      not null
#  type                            :string(255)
#  crypted_password                :string(255)
#  salt                            :string(255)
#  remember_me_token               :string(255)
#  reset_password_token            :string(255)
#  reset_password_token_expires_at :datetime
#  reset_password_email_sent_at    :datetime
#  remember_me_token_expires_at    :datetime
#  created_at                      :datetime
#  updated_at                      :datetime
#

class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :posts
  has_many :tags, through: :posts
  has_many :categories

  accepts_nested_attributes_for :tags,
                                reject_if: :all_blank,
                                allow_destroy: true
  accepts_nested_attributes_for :categories,
                                reject_if: :all_blank,
                                allow_destroy: true
  validates :name,
            length: { maximum: 8 },
            presence: true

  validates :email,
            presence: true,
            uniqueness: true

  validates :password,
            presence: true,
            length: { minimum: 8 },
            confirmation: true,
            if: :new_record_or_changes_password

  validates :password_confirmation,
            presence: true,
            if: :new_record_or_changes_password

  private

  def new_record_or_changes_password
    new_record? || changes[:crypted_password]
  end
end

app/controllers/blog/posts_controller.rb
class Blog::PostsController < ApplicationController
  before_action :set_categories, only: [:index, :show]

  def index
    @posts = Kaminari.paginate_array(admin.posts.decorate).page(params[:page])
    @tags = admin.posts.tag_counts_on(:tags).order('count DESC')
    @recent_posts = @posts[0..Post::RECENT_POSTS_CONT]
  end

  def show
    @post = admin.posts.find(params[:id]).decorate
  end

  def tag_cloud
    @tags = Post.tag_counts_on(:tags).order('count DESC')
  end

  private

  def set_categories
    @categories = admin.categories.all
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  layout 'users/layouts/application'
end

app/controllers/users/categories_controller.rb
class Users::CategoriesController < UserController
  before_action :require_login

  def index
    @categories = current_user.categories
  end

  def new
    current_user.categories.build if current_user.categories.empty?
  end

  def create
    current_user.update(category_params)
    respond_with current_user, location: users_categories_path, method: :get
  end

  private

  def category_params
    params.require(:admin).permit(
      categories_attributes: [:id, :parent_id, :name, :_destroy]
    )
  end
end

app/controllers/users/posts_controller.rb
class Users::PostsController < UserController
  before_action :require_login
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = current_user.posts.decorate
  end

  def show
  end

  def new
    @post = current_user.posts.build
    @categories = current_user.categories
  end

  def create
    @post = current_user.posts.create(post_params)
    respond_with @post, location: users_post_path(@post)
  end

  def update
    @post.update(post_params)
    respond_with @post, location: users_post_path(@post)
  end

  def destroy
    @post = @post.destroy
    respond_with @post, location: users_posts_path
  end

  private

  def set_post
    @post = current_user.posts.find(params[:id]).decorate
  end

  def post_params
    permited_params = params.require(:post).permit(:title, :category_id, :body, :tag_list)
    # FIXME: tag_listが空になるため以下の処理を追加
    permited_params[:tag_list] = params[:post][:tag_list]
    permited_params[:status] = convert_status
    permited_params
  end

  def convert_status
    params[:commit] == I18n.t('enumerize.post.status.wip') ? 'wip' : 'published'
  end
end

app/controllers/users/sign_in_controller.rb
class Users::SignInController < UserController
  skip_before_action :require_login

  def show
    @user = User.new
  end

  def create
    email, password = params[:user].values_at(:email, :password)
    @user = login(email, password)

    if @user.blank?
      @user = User.new(email: email).tap do |user|
        user.errors.add(:email, :not_found_or_invalid_password)
      end
      return render :show
    end

    respond_with @user, location: users_path, notice: 'サインインしました'
  end
end

app/controllers/users/sign_out_controller.rb
class Users::SignOutController < UserController
  def destroy
    logout
    redirect_to users_sign_in_url
  end
end

app/controllers/users/sign_up_controller.rb
class Users::SignUpController < UserController
  skip_before_action :require_login

  def show
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    return render :show if @user.errors.present?

    respond_with @user, location: edit_users_path, notice: 'サインインアップしました'
  end

  private

  def user_params
    params.require(:user).permit(
      :name, :email, :password, :password_confirmation
    )
  end
end

app/controllers/users/tags_controller.rb
class Users::TagsController < UserController
  before_action :require_login

  def index
    @tags = current_user.tags.order('taggings_count DESC')
  end

  def new
  end

  def create
    current_user.update(tag_params)
    respond_with current_user, location: users_tags_path, method: :get
  end

  def list
    render json: current_user.tags.pluck(:name).to_json
  end

  private

  def tag_params
    params.require(:admin).permit(
      tags_attributes: [:id, :name, :_destroy]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < UserController
  before_action :require_login

  def edit
  end

  def update
    current_user.update(user_params)
    respond_with current_user, location: users_path
  end

  private

  def user_params
    params.require(:admin).permit(:name, :email)
  end
end

app/helpers/blog/post_helper.rb
module Blog::PostHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users/categories_helper.rb
module Users::CategoriesHelper
  def nested_categories(categories)
    categories.map do |category, sub_categories|
      render(category) + content_tag(
        :div, nested_categories(sub_categories),
        class: 'nested_categories'
      )
    end.join.html_safe
  end

  def selectable_categories(category)
    categories = current_user.categories.where.not(id: category.id)
    categories.to_a.insert(0, Category.root)
  end
end

app/helpers/users/posts_helper.rb
module Users::PostsHelper
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
end

app/helpers/users/sign_in_helper.rb
module Users::SignInHelper
end

app/helpers/users/sign_out_helper.rb
module Users::SignOutHelper
end

app/helpers/users/sign_up_helper.rb
module Users::SignUpHelper
end

app/helpers/users/tags_helper.rb
module Users::TagsHelper
end

app/views/users/posts/_form.html.slim
= simple_form_for post, url: url, method: method do |form|
  .row
    .col-md-8
      .panel.panel-default
        .panel-heading 新規作成
        .panel-body
          .panel.panel-default
            .panel-heading = Post.human_attribute_name(:title)
            .panel-body
              = form.input :title, label: false, input_html: { required: true }
          .panel.panel-default
            .panel-heading = Post.human_attribute_name(:body)
            .panel-body
              = form.input :body, label: false, input_html: { rows: 30 }
              .btn-toolbar
                = form.submit 'WIP', status: 0, class: %w(btn btn-default)
                = form.submit '公開', status: 1, class: %w(btn btn-primary)
    .col-md-4
      = render 'side_bar', form: form

app/views/users/posts/_side_bar.html.slim
.panel.panel-default
  .panel-heading = Category.model_name.human
  .panel-body
    = form.input :category_id, collection: current_user.categories, label: false, include_blank: true, input_html: { class: 'searchable', required: true }
  .panel.panel-default
    .panel-heading = Tag.model_name.human
    .panel-body
      = form.input :tag_list, label: false, input_html: {id: 'js-tag-magicsuggest', value: @post.tag_list.to_s }, class: 'required'

app/views/users/posts/edit.html.slim
h1 class='page-header' マイページ
= render 'form', post: @post, url: users_post_path, method: :patch

app/views/users/posts/index.html.slim
h1 class='page-header' マイページ
.row
  .col-md-4.col-xs-4
    = render 'users/menue', active: :post
  .col-md-8.col-xs-8
    .panel.panel-default
      .panel-heading
        '記事一覧
      .panel-body
        = link_to '新規記事作成', new_users_post_path, class: %w(btn btn-success)
        .list-group
        - if @posts.empty?
           .list-group-item 記事がありません
        - else
          - @posts.each do |post|
            .list-group-item.row
              .col-md-6.col-xs-6
                = post.title
              .col-md-1.col-xs-1
                = post.status_label
              .col-md-2.col-xs-2
                = post.updated_at.to_s(:YYYYmmdd)
              .col-md-3.col-xs-3.row
                .col-md-4.col-xs-4
                  = link_to '', users_post_path(post), class: %w(glyphicon glyphicon-list-alt)
                .col-md-4.col-xs-4
                  = link_to '', edit_users_post_path(post), class: %w(glyphicon glyphicon-pencil)
                .col-md-4.col-xs-4
                  = link_to '', users_post_path(post), method: :delete, class: %w(glyphicon glyphicon-trash)

app/views/users/posts/new.html.slim
h1 class='page-header' マイページ
= render 'form', post: @post, url: users_posts_path, method: :post

app/views/users/posts/show.html.slim
h1 class='page-header' マイページ
.row
  .col-md-8
    .panel.panel-default
      .panel-heading 記事詳細
      .panel-body
        .btn-toolbar
          = link_to '一覧', users_posts_path, class: %w(btn btn-default)
          = link_to '編集', edit_users_post_path(@post), class: %w(btn btn-success)
        hr
        .panel.panel-default
          .panel-heading = Post.human_attribute_name(:title)
          .panel-body
            .row
              .col-md-9
                = @post.title
              .col-md-1
                = @post.status_label
              .col-md-2
                = @post.updated_at.to_s(:YYYYmmdd)
        .panel.panel-default
          .panel-heading = Post.human_attribute_name(:body)
          .panel-body
            .row
              .col-md-12
                = @post.body_as_html
  .col-md-4
    .panel.panel-default
      .panel-heading = Category.model_name.human
      .list-group
        .list-group-item
          = @post.category.name
    .panel.panel-default
      .panel-heading = Tag.model_name.human
      .list-group
      - if @post.tag_list.empty?
         .list-group-item タグがありません
      - else
        - @post.tag_list.each do |tag_name|
          .list-group-item
            = @post.tag_label(tag_name)