config/routes.rb
# == Route Map
#
#              Prefix Verb   URI Pattern                          Controller#Action
#                root GET    /                                    home#index
#               about GET    /about(.:format)                     about#index
#       users_sign_up POST   /users/sign_up(.:format)             users/sign_up#create
#                     GET    /users/sign_up(.:format)             users/sign_up#show
#       users_sign_in POST   /users/sign_in(.:format)             users/sign_in#create
#                     GET    /users/sign_in(.:format)             users/sign_in#show
#      users_sign_out DELETE /users/sign_out(.:format)            users/sign_out#destroy
#         users_posts GET    /users/posts(.:format)               users/posts#index
#                     POST   /users/posts(.:format)               users/posts#create
#      new_users_post GET    /users/posts/new(.:format)           users/posts#new
#     edit_users_post GET    /users/posts/:id/edit(.:format)      users/posts#edit
#          users_post GET    /users/posts/:id(.:format)           users/posts#show
#                     PATCH  /users/posts/:id(.:format)           users/posts#update
#                     PUT    /users/posts/:id(.:format)           users/posts#update
#                     DELETE /users/posts/:id(.:format)           users/posts#destroy
#    users_categories GET    /users/categories(.:format)          users/categories#index
#                     POST   /users/categories(.:format)          users/categories#create
#  new_users_category GET    /users/categories/new(.:format)      users/categories#new
# edit_users_category GET    /users/categories/:id/edit(.:format) users/categories#edit
#      users_category GET    /users/categories/:id(.:format)      users/categories#show
#                     PATCH  /users/categories/:id(.:format)      users/categories#update
#                     PUT    /users/categories/:id(.:format)      users/categories#update
#                     DELETE /users/categories/:id(.:format)      users/categories#destroy
#          users_tags GET    /users/tags(.:format)                users/tags#index
#                     POST   /users/tags(.:format)                users/tags#create
#       new_users_tag GET    /users/tags/new(.:format)            users/tags#new
#      tag_list_users GET    /users/tag/list(.:format)            users/tags#list
#          edit_users GET    /users/edit(.:format)                users#edit
#               users GET    /users(.:format)                     users#show
#                     PATCH  /users(.:format)                     users#update
#                     PUT    /users(.:format)                     users#update
#                     DELETE /users(.:format)                     users#destroy
#          blog_posts GET    /blog/posts(.:format)                blog/posts#index
#           blog_post GET    /blog/posts/:id(.:format)            blog/posts#show
#       blog_category GET    /blog/categories/:id(.:format)       blog/categories#show
#            blog_tag GET    /blog/tags/:id(.:format)             blog/tags#show
#

Rails.application.routes.draw do
  root 'home#index'
  get 'profile', to: 'profile#index'

  resource :users, only: [:show, :edit, :update, :destroy] do
    resource :sign_up, controller: 'users/sign_up', only: [:show, :create]
    resource :sign_in, controller: 'users/sign_in', only: [:show, :create]
    resource :sign_out, controller: 'users/sign_out', only: [:destroy]
    resources :posts, controller: 'users/posts'
    resources :categories, controller: 'users/categories'
    resources :tags, controller: 'users/tags', only: [:index, :create, :new]
    get 'tag/list', to: 'users/tags#list'
  end

  namespace :blog do
    resources :posts, only: [:index, :show]
    resources :categories, only: [:show]
    resources :tags, only: [:show]
  end
end

app/controllers/blog/categories_controller.rb
class Blog::CategoriesController < ApplicationController
  def show
    @category = admin.categories.find(params[:id])
    @categories = admin.categories.all
    @posts = Kaminari.paginate_array(
      admin.posts.where(category_id: params[:id]).decorate
    ).page(params[:page])
    @tags = admin.posts.tag_counts_on(:tags).order('count DESC')
    @recent_posts = @posts[0..Post::RECENT_POSTS_CONT]
  end
end

app/controllers/blog/posts_controller.rb
class Blog::PostsController < ApplicationController
  before_action :set_categories, only: [:index, :show]

  def index
    @posts = Kaminari.paginate_array(admin.posts.decorate).page(params[:page])
    @tags = admin.posts.tag_counts_on(:tags).order('count DESC')
    @recent_posts = @posts[0..Post::RECENT_POSTS_CONT]
  end

  def show
    @post = admin.posts.find(params[:id]).decorate
  end

  def tag_cloud
    @tags = Post.tag_counts_on(:tags).order('count DESC')
  end

  private

  def set_categories
    @categories = admin.categories.all
  end
end

app/controllers/blog/tags_controller.rb
class Blog::TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
    @categories = admin.categories.all
    @posts = Kaminari.paginate_array(
      admin.posts.where(category_id: params[:id]).decorate
    ).page(params[:page])
    @tags = admin.posts.tag_counts_on(:tags).order('count DESC')
    @recent_posts = @posts[0..Post::RECENT_POSTS_CONT]
  end
end

app/helpers/blog/categories_helper.rb
module Blog::CategoriesHelper
end

app/helpers/blog/post_helper.rb
module Blog::PostHelper
end

app/helpers/blog/tags_helper.rb
module Blog::TagsHelper
end

app/views/blog/shared/_article.html.slim
.article
  .row.article-header
    h4 class='title'
      = link_to post.title, blog_post_path(post), class: 'coloer-black'
    .title-details
      .col-md-3
        = fa_icon 'calendar', class: 'icon'
        = post.published_at
      .col-md-3
        = fa_icon 'folder-open-o', class: 'icon'
        = link_to post.category.name, blog_category_path(post.category)
      .col-md-6
        = fa_icon 'tags', class: 'icon'
        - post.tags.each do |tag|
          = link_to "##{tag.name} ", blog_tag_path(tag)
  .article-text
    = post.body_as_html

app/views/blog/shared/_index.html.slim
.col-xs-7
  - if posts.present?
    - posts.each do |post|
      = render 'blog/shared/article', post: post
    .center-block
      = paginate posts
  - else
    '#{Post.model_name.human}はありません。
.col-xs-5
  = render 'blog/shared/sidebar', posts: posts, recent_posts: recent_posts, tags: tags

app/views/blog/shared/_sidebar.html.slim
.sidebar
  .panel.panel-default
    .panel-heading
      = fa_icon 'pencil-square-o ', class: 'icon'
      = "最近の#{Post.model_name.human}"
    .panel-body
      ul
        - if recent_posts.present?
          - recent_posts.each do |recent_post|
            li
              = link_to recent_post.title, blog_post_path(recent_post)
        - else
          '最近の#{Post.model_name.human}はありません。

  .panel.panel-default
    .panel-heading
      = fa_icon 'folder-open-o', class: 'icon'
      = Category.model_name.human
    .panel-body
      ul
        - if @categories.present?
          - @categories.each do |category|
            li
              = link_to category.name, blog_category_path(category)
              span class='badge'
                = category.posts.size
        - else
          '#{Category.model_name.human}はありません。

  .panel.panel-default
    .panel-heading
      = fa_icon 'tags', class: 'icon'
      = Tag.model_name.human
    .panel-body
      - if tags.present?
        - tag_cloud(tags, %w(s m l xl)) do |tag, css_class|
          = link_to "#{tag.name}(#{tag.count}) ", blog_tag_path(tag), class: css_class
      - else
        ul
          '#{Tag.model_name.human}はありません。