config/routes.rb
# == Route Map
#
#              Prefix Verb   URI Pattern                          Controller#Action
#                root GET    /                                    home#index
#               about GET    /about(.:format)                     about#index
#       users_sign_up POST   /users/sign_up(.:format)             users/sign_up#create
#                     GET    /users/sign_up(.:format)             users/sign_up#show
#       users_sign_in POST   /users/sign_in(.:format)             users/sign_in#create
#                     GET    /users/sign_in(.:format)             users/sign_in#show
#      users_sign_out DELETE /users/sign_out(.:format)            users/sign_out#destroy
#         users_posts GET    /users/posts(.:format)               users/posts#index
#                     POST   /users/posts(.:format)               users/posts#create
#      new_users_post GET    /users/posts/new(.:format)           users/posts#new
#     edit_users_post GET    /users/posts/:id/edit(.:format)      users/posts#edit
#          users_post GET    /users/posts/:id(.:format)           users/posts#show
#                     PATCH  /users/posts/:id(.:format)           users/posts#update
#                     PUT    /users/posts/:id(.:format)           users/posts#update
#                     DELETE /users/posts/:id(.:format)           users/posts#destroy
#    users_categories GET    /users/categories(.:format)          users/categories#index
#                     POST   /users/categories(.:format)          users/categories#create
#  new_users_category GET    /users/categories/new(.:format)      users/categories#new
# edit_users_category GET    /users/categories/:id/edit(.:format) users/categories#edit
#      users_category GET    /users/categories/:id(.:format)      users/categories#show
#                     PATCH  /users/categories/:id(.:format)      users/categories#update
#                     PUT    /users/categories/:id(.:format)      users/categories#update
#                     DELETE /users/categories/:id(.:format)      users/categories#destroy
#          users_tags GET    /users/tags(.:format)                users/tags#index
#                     POST   /users/tags(.:format)                users/tags#create
#       new_users_tag GET    /users/tags/new(.:format)            users/tags#new
#      tag_list_users GET    /users/tag/list(.:format)            users/tags#list
#          edit_users GET    /users/edit(.:format)                users#edit
#               users GET    /users(.:format)                     users#show
#                     PATCH  /users(.:format)                     users#update
#                     PUT    /users(.:format)                     users#update
#                     DELETE /users(.:format)                     users#destroy
#          blog_posts GET    /blog/posts(.:format)                blog/posts#index
#           blog_post GET    /blog/posts/:id(.:format)            blog/posts#show
#       blog_category GET    /blog/categories/:id(.:format)       blog/categories#show
#            blog_tag GET    /blog/tags/:id(.:format)             blog/tags#show
#

Rails.application.routes.draw do
  root 'home#index'
  get 'profile', to: 'profile#index'

  resource :users, only: [:show, :edit, :update, :destroy] do
    resource :sign_up, controller: 'users/sign_up', only: [:show, :create]
    resource :sign_in, controller: 'users/sign_in', only: [:show, :create]
    resource :sign_out, controller: 'users/sign_out', only: [:destroy]
    resources :posts, controller: 'users/posts'
    resources :categories, controller: 'users/categories'
    resources :tags, controller: 'users/tags', only: [:index, :create, :new]
    get 'tag/list', to: 'users/tags#list'
  end

  namespace :blog do
    resources :posts, only: [:index, :show]
    resources :categories, only: [:show]
    resources :tags, only: [:show]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.published.order(created_at: :desc).limit(Post::LATEST_POSTS_COUNT).decorate
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.slim
#drawer-right
  .cross.text-right
    a.toggleDrawer href="#"
      i.fa.fa-times-circle.fa-2x
  h2 Navigate
  nav
    ul.nav.nav-pills.nav-stacked
      li
        a href="#wrapper"
          i.fa.fa-home
            '  Home
      li
        a href="#portfolio"
          i.fa.fa-bookmark
            '  Portfolio
      li
        a href="#blog"
          i.fa.fa-wordpress
            '  Blog
      li
        a href="#contact"
          i.fa.fa-phone-square
            '  Contact
  .social
    h2 Stay Connected
    ul
      li
        = link_to 'https://www.facebook.com/takita.yusuke' do
          i.fa.fa-facebook-square.fa-3x
      li
        = link_to root_path do
          i.fa.fa-twitter-square.fa-3x

#wrapper
  #header.content-block.header-wrapper
    .header-wrapper-inner
      section.top.clearfix
        /.pull-left
          h1
            = link_to root_path do
              /logo
        .pull-right
          a.toggleDrawer href="#"
            i.fa.fa-bars.fa-2x
      section.center
        .slogan
          'Yusuke takita's portfolio
        /.secondary-slogan
          | The Flusk Theme By ThemeWagon.
      section.bottom
        = link_to '#', id: 'scrollToContent' do
          = image_tag asset_path('images/arrow_down.png')

  #portfolio.content-block
    .container
      header.block-heading.cleafix
        a.btn.btn-o.btn-lg.pull-right href="#"  View All
        h1 Latest Works
        p Take a look at some of my recent works
      section.block-body
        .row
          .col-sm-4
            a.recent-work href="#" style="background-image:url(#{asset_path('images/rain_1-320x240.jpg')})"
              span.btn.btn-o-white More detail
          .col-sm-4
            a.recent-work href="#" style="background-image:url(#{asset_path('images/min_icons_thumb1-320x240.jpg')})"
              span.btn.btn-o-white More detail
          .col-sm-4
            a.recent-work href="#" style="background-image:url(#{asset_path('images/flat_icons_thumb.jpg')})"
              span.btn.btn-o-white More detail

  #services.content-block.parallax
    .container.text-center
      header.block-heading.cleafix
        h1 Profile
        p A little about what I do
      section.block-body
        .row
          .col-md-4
            .service
              i.fa.fa-code
              h2 Engineer
              p ERPのHR領域のエンジニアから<br>Webエンジニアになりました。<br>おもにRuby on Railsを触ってます。
          .col-md-4
            .service
              i.fa.fa-futbol-o
              h2 Footballer
              p 趣味でフットサルをやります。<br>安定した守備とビルドアップを提供しますので、<br>助っ人が必要な時はお声がけください。
          .col-md-4
            .service
              i.fa.fa-book
              h2 Books
              p 本を読むのが好きです。<br>エンジニアになる前は、<br>経営学に関する本をよく読んでいたので、<br>その領域の主要な本は読んでいます。<br>（という勘違いをしています）

  #blog.content-block
    .container
      header.block-heading.cleafix
        = link_to 'View All', blog_posts_path, class: %w(btn btn-o btn-lg pull-right), target: '_blank'
        h1 Latest posts
        p Keep up with the latest happenings.
      section.block-body
        .row
          - @posts.each_with_index do |post, i|
            .col-sm-4.blog-post
              = link_to blog_post_path(post) do
                // TODO: いったんアイキャッチは固定
                = image_tag asset_path(post.eye_catch_img_path(i))
              h2 = post.title
              .date = post.updated_at.to_s(:YYYYmmdd)
              p = post.body.truncate(60)
              = link_to 'Read More', blog_post_path(post)

  #contact.content-block
    .container.text-center
      header.block-heading.cleafix
        h1 Contact Us
        p Feel free to drop me a line.
      section.block-body
        .row
          .col-md-6.col-md-offset-3
            form role="form"
              .form-group
                input#subject.form-control.form-control-white placeholder=("Your Name") required="" type="email" /
              .form-group
                input#exampleInputEmail2.form-control.form-control-white placeholder=("Enter email") required="" type="email" /
              .form-group
                textarea.form-control.form-control-white placeholder=("Write Something") required=""
              input.btn.btn-o-white type="submit" value=("Say Hello") /

  #footer.content-block
    .container
      .row
        .col-xs-6 &copy; 2017 Yusuke Takita
        .col-xs-6.text-right Powered by Nginx x Ruby on Rails